---

- name: Lauch AWS Infrastructure
  hosts: localhost
  connection: local
  gather_facts: False


## Provide variable files
  vars_files:
    - configs/aws_credentials.yml
    - configs/vars.yml

  tasks:

  - name: Administrador_SG_brasil
    ec2_group:
      ec2_access_key: "{{ AWS_ACCESS_KEY_ID }}"
      ec2_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
      name: Administrador_SG_brasil
      description: "A Security group of San Paulo region"
      region: "{{ ec2_region }}"
      rules:
        - proto: tcp
          from_port: 22
          to_port: 22
          cidr_ip: 0.0.0.0/0
        - proto: tcp
          from_port: 5601
          to_port: 5601
          cidr_ip: 0.0.0.0/0
        - proto: tcp
          from_port: 9200
          to_port: 9200
          cidr_ip: 0.0.0.0/0
        - proto: tcp
          from_port: 8081
          to_port: 8081
          cidr_ip: 0.0.0.0/0
    register: basic_firewall

  - name: Create EC-2 instance
    ec2:
      ec2_access_key: "{{ AWS_ACCESS_KEY_ID }}"
      ec2_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
      region: "{{ ec2_region }}"
      group_id: "{{ basic_firewall.group_id }}"   
      instance_type: t2.micro
      image: "{{ ami_id }}"
      key_name: "{{ key_name }}"
      instance_tags:
            Name: manchester_instance
      exact_count: 1
      count_tag:
            Name: manchester_instance
      wait: true
    register: ec2
