---

- name: Deploy application
  hosts: ec2_instance
  remote_user: ubuntu
  gather_facts: False


  tasks:

    - name: Copy application from ansible server to the new instance EC2
      copy: src=docker/app dest=/home/ubuntu/
